### ISSUE TITLE
UnicodeDecodeError when connecting to GeoNode Geoserver

### ISSUE THREAD

**Issue by dvictori** [boundlessgeo/qgis-geoserver-plugin#43] opened 2016-06-29 18:46 UTC
I have a Geonode 2.4 installed in Ubuntu with 108 registered layers. All seems to be running OK. I then tryed to connect to the GeoServer using GeoServer Explorer Plugin, installed from the QGis plugin repository. I'm running QGis 2.14.3 in Win10.

When connecting to the catalog I get a short list of layers and the following error:

```
Traceback (most recent call last):
  File "C:/Users/m330625/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
    command(*params)
  File "C:/Users/m330625/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 534, in populate
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 462: ordinal not in range(128)
```

My GeoServer getCapabilities is attached.

[getcapabilities_1.3.0.txt](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/339947/getcapabilities_1.3.0.txt)

**Comment by gioman** [comment] 2017-03-23 21:57
possibly related to https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/44

**Comment by gioman** [comment] 2017-05-04 14:12
duplicate of #44

**Closed by gioman** 2017-05-04 14:12 UTC
Labels: bug
