### ISSUE TITLE
band conversion during raster upload to geoserver

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#13] opened 2015-10-21 17:43 UTC
ploease verify (assigned temporarly to Victor)

Uploading (wcs) a .img with a single band (alaska.img from qgis test data), it is converted to GeoTIFF.
This could not be a problem if the the other added bands are NULL values. But the Histogram is changed.

attached the first histogram of the original .img
![screenshot from 2015-10-21 19 18 26](https://cloud.githubusercontent.com/assets/3344634/10644918/52f4c018-782b-11e5-908b-e40fd39ade80.png)

and here the recovered image
![screenshot from 2015-10-21 19 19 19](https://cloud.githubusercontent.com/assets/3344634/10644928/603005c6-782b-11e5-9e0b-6ee6a8461b63.png)

I supposed it was a resolution problem due the fact that the image is NOT get at full resolution but almos 1/10th resolution. I supposed a qgis trategy to create WCS call.
But nothing is changed zooming to a pixeled area where I suppose it would get at full resolution the resctricted extent area.

so... seems that the "upload" tranfrom data to be unusable as the original one.

I don't know if it's a plugin problem, a geoserver problem or a wcs limitation... so I can't assign and I can't say if it's a valid issue. please verify

**Comment by volaya** [comment] 2015-10-22 05:38
A way to verify this would be to do the same wrokflow, without using the plugin. That is:

- upload to GeoServer using the web interface
-Create a WCS layer from the uploaded layer using the "Add new WCS layer" QGIS menu

If the result is the same, then the problem is not in the plugin, and we should fill a ticket in the QGIS or GeoServer trackers

@luipir can you try that?

**Comment by luipir** [comment] 2015-10-22 11:37
I tested using geserver dashboard... but .img is not supported as direct format (seems only gtiff?)
gdalinfo of the original give 1 band with value from 0 to 13
[landcover.txt](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/18470/landcover.txt)

saving .img using core "saveas" (without any option) generate a gtiff with the same statistic (it just loos color palette)

.img is imported in geoserver using QgsRasterFileWriter seems assuming default convertion parameters that:
1) stretch the image
2) strech the bands

can be considered a bug? 

I'll check the "saveas" core way to create the gtiff

**Comment by luipir** [comment] 2015-10-22 11:51
I think the solution is in setting rowMode of the qgsFileWriter as here:
https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L5328

**Comment by alexbruy** [comment] 2016-02-04 18:20
I implemented correct raster export and now waiting when https://hub.qgis.org/issues/14210 will be fixed in QGIS.

**Comment by gioman** [comment] 2016-12-01 18:10
@alexbruy @volaya @luipir the upstream bug fix is still open.

**Comment by gioman** [comment] 2017-03-23 21:25
> I implemented correct raster export and now waiting when https://hub.qgis.org/issues/14210 will be fixed in QGIS.

@alexbruy @luipir I recently tested that upstream issue in 2.18.4 and seemed fine to me. Can we close this?

**Comment by gioman** [comment] 2017-05-04 14:40
assuming that this ca be closed.

**Closed by gioman** 2017-05-04 14:40 UTC
Labels: bug, question
